### ISSUE TITLE
Add support for multiple coverage file

### ISSUE THREAD

**Issue by StephaneG31** [jenkinsci/cobertura-plugin#104] opened 2018-09-13 12:51 UTC
In my project, in the same job we build .net and Angular Project. So we have two cobertura report.
Please add some params to speciy the directory for cobertura report and for the cobertura report name (in the sidebar).
Maybe there are some others impacts to develop

**Comment by zgriesinger** [comment] 2018-12-05 20:57
I was able to use two with syntax like this (CSV), however they are merged not distinct
```jenkinsfile
steps {
  cobertura coberturaReportFile: 'path/to/cobertura-coverage.xml,path/to/second-cobertura-coverage.xml'
}
```

**Comment by ViceIce** [comment] 2019-05-21 11:02
We would like to have this too, because we are building out frontend and backend on seperate agents.

If we simply stash the reports, some sources are not available after import, because build path  changes.

So it would be nice to be able to import multiple times.

**Comment by ViceIce** [comment] 2019-05-21 11:17
looks like a duplicate of #82

**Comment by jeffpearce** [comment] 2019-05-21 13:06
Closing as a dup of #82

**Closed by jeffpearce** 2019-05-21 13:06 UTC
