### ISSUE TITLE
Source code is unavailable no matter what I do

### ISSUE THREAD

**Issue by GabLeRoux** [jenkinsci/cobertura-plugin#61] opened 2016-11-24 00:09 UTC
I'm using #55 and everything seems to work fine, I see coverage results in jenkins with cool graphs, but I can't manage to get the sources to display in jenkins.

```
Source

Source code is unavailable. Some possible reasons are:

This is not the most recent build (to save on disk space, this plugin only keeps the most recent build’s source code).
Cobertura found the source code but did not provide enough information to locate the source code.
Cobertura could not find the source code, so this plugin has no hope of finding it.
You do not have sufficient permissions to view this file.
```

![image](https://cloud.githubusercontent.com/assets/1264761/20582430/21526eac-b1af-11e6-8dca-6de049714644.png)

There are a few related old issues:
#29 
#38 

There is this closed issue:
https://issues.jenkins-ci.org/browse/JENKINS-5235

My `coverage.xml` does have a valid path in sources:source tag. I was able to `ls` the sources from the path in the file.
```xml
        <sources>
                <source>/var/lib/jenkins/workspace/e-HTHYJUZDZMCL63QUXR6Q5QZPTK4AQEV3NNTYGGY2FQSB27WHP6ZA/MyAppName</source>
        </sources>
```

(only works with #55)
```groovy
step([$class: 'CoberturaPublisher', coberturaReportFile: 'MyAppName/reports/coverage.xml'])
```

**Comment by v-lopez** [comment] 2016-11-30 14:22
On my installation, I found out that only users with admin privilege can see the source code. Might be relevant to you.

**Comment by GabLeRoux** [comment] 2016-12-05 16:30
Oh thanks for your answer, I missed that notification. I'm pretty sure my user is admin as I'm able to install plugins and manage the whole instance. I'll install the [Role Strategy Plugin|https://wiki.jenkins-ci.org/display/JENKINS/Role+Strategy+Plugin] just to make sure.

If I find some time, I'll try this on a clean jenkins install without using pipeline and see if it works. I'll try with and without #55.

**Comment by Jean-Daniel** [comment] 2016-12-12 17:11
Did just install the modified cobertura plugin and have the same issue here. It works with the old plugin working in a old style job, but not with the new plugin working in a pipeline job, so this is definitively not a user permission issue.

**Comment by mbarrien** [comment] 2017-01-31 22:19
Try the latest commit from #55 . Should have fixed your issue.

**Comment by mbarrien** [comment] 2017-04-25 16:50
Closed in #55/#62. Not yet released as official plugin but coming soon.

**Closed by mbarrien** 2017-04-25 16:50 UTC

**Comment by mfuchs** [comment] 2018-07-11 17:12
I have the same issue with the most recent version.
Users with admin rights can see the the source code.
Users without admin rights cannot.

This happens for a multibranch pipeline job.

**Comment by ewortzman** [comment] 2018-08-30 16:43
This doesn't seem to be resolved.  I'm still seeing that only users with admin privileges can view source code.  Is this by design? If so, can someone defend that design decision? It doesn't seem to make any sense.

**Comment by ThrashAbaddon** [comment] 2019-01-14 12:56
Also having problems

**Comment by marcofiocco** [comment] 2019-02-20 06:36
Same here

**Comment by xiaojia1203** [comment] 2019-05-27 02:48
same here

**Comment by jhagege** [comment] 2019-07-17 07:32
+1

**Comment by tiwari85aman** [comment] 2019-07-17 07:43
I am also having this issue in PIPELINE jobs.

**Comment by jhagege** [comment] 2019-07-17 10:44
https://stackoverflow.com/a/27859112/3626406

> +1

**Comment by onlyou2030** [comment] 2022-07-25 02:38
same here
